name: just_bottom_sheet
description: Flexible bottom sheet widget, that does nothing redundant
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic91:
    git:
      url: https://github.com/91team/pedantic91.git
      ref: v0.1.2
  flutter_test:
    sdk: flutter
